services:
  ewm-service:
    build: ./ewm-main-service
    image: main-image
    container_name: main-container
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
      - stats-server
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/main
      - STATS_URL=http://stats-server:9090

  stats-server:
    build: ./ewm-stats-service/server
    image: stats-server-image
    container_name: stats-server-container
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stats

  stats-db:
    image: postgres:16.1
    container_name: stats-db-container
    ports:
      - "5432:5432"
    volumes:
      - /var/lib/postgresql/stats
    environment:
      - POSTGRES_DB=stats
      - POSTGRES_USER=stats_user
      - POSTGRES_PASSWORD=stats_pass
  ewm-db:
    image: postgres:16.1
    container_name: main-db-container
    ports:
      - "5433:5432"
    volumes:
      - /var/lib/postgresql/main
    environment:
      - POSTGRES_DB=main
      - POSTGRES_USER=main_user
      - POSTGRES_PASSWORD=main_pass