drop table IF EXISTS "user" CASCADE;
drop table IF EXISTS category CASCADE;
drop table IF EXISTS location CASCADE;
drop table IF EXISTS "event" CASCADE;
drop table IF EXISTS "compilation" CASCADE;
drop table IF EXISTS "compilation_event" CASCADE;
drop table IF EXISTS "request" CASCADE;
drop table IF EXISTS "comment" CASCADE;

CREATE TABLE IF NOT EXISTS "user"(
                                    id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                    name  VARCHAR(250) not null,
                                    email VARCHAR(254) UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS category(
                                         id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                         name VARCHAR(50) UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS location(
                                        id  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                        lat NUMERIC,
                                        lon NUMERIC
);

CREATE TABLE IF NOT EXISTS event (
                                      id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
                                      annotation VARCHAR(2000) NOT NULL,
                                      cat_id BIGINT NOT NULL REFERENCES category(id) ON UPDATE CASCADE,
                                      confirmed_requests INTEGER,
                                      created_on TIMESTAMP,
                                      description VARCHAR(7000),
                                      event_date TIMESTAMP NOT NULL,
                                      initiator BIGINT NOT NULL REFERENCES "user"(id) ON UPDATE CASCADE ON DELETE CASCADE,
                                      location BIGINT NOT NULL REFERENCES location(id) ON UPDATE CASCADE ON DELETE CASCADE,
                                      paid BOOLEAN NOT NULL,
                                      participant_limit INTEGER DEFAULT 0,
                                      published_on TIMESTAMP WITHOUT TIME ZONE,
                                      request_moderation BOOLEAN DEFAULT TRUE,
                                      state VARCHAR(20),
                                      title VARCHAR(120) NOT NULL,
                                      views BIGINT
);

CREATE TABLE IF NOT EXISTS compilation (
                                            id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
                                            pinned BOOLEAN,
                                            title VARCHAR(50)
);

CREATE TABLE IF NOT EXISTS compilation_event (
                                           id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
                                           compilation_id BIGINT NOT NULL REFERENCES compilation(id) ON UPDATE CASCADE ON DELETE CASCADE,
                                           event_id BIGINT NOT NULL REFERENCES "event"(id) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS request (
                                        id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
                                        requester_id BIGINT NOT NULL REFERENCES "user"(id) ON UPDATE CASCADE ON DELETE CASCADE,
                                        event_id BIGINT NOT NULL REFERENCES "event"(id) ON UPDATE CASCADE ON DELETE CASCADE,
                                        created TIMESTAMP NOT NULL,
                                        status VARCHAR(20) NOT NULL
);

CREATE TABLE IF NOT EXISTS comment (
                                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                        text TEXT NOT NULL,
                                        status VARCHAR(20) NOT NULL,
                                        created TIMESTAMP NOT NULL,
                                        event_id BIGINT NOT NULL REFERENCES "event"(id),
                                        user_id BIGINT NOT NULL REFERENCES "user"(id)
);