drop table IF EXISTS "user";
drop table IF EXISTS category;

CREATE TABLE IF NOT EXISTS "user"(
                                    id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                    name  VARCHAR(250) not null,
                                    email VARCHAR(254) UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS category(
                                         id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                         name VARCHAR(50) UNIQUE NOT NULL
);